"""empty message

Revision ID: 5c54e2f62083
Revises: a720f41a6bd4
Create Date: 2022-02-08 11:39:35.297512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54e2f62083'
down_revision = 'a720f41a6bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post_likes')
    op.add_column('follows', sa.Column('userid', sa.Integer(), nullable=False))
    op.add_column('follows', sa.Column('followedid', sa.Integer(), nullable=False))
    op.drop_constraint('follows_userId_fkey', 'follows', type_='foreignkey')
    op.drop_constraint('follows_followedId_fkey', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['followedid'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['userid'], ['id'])
    op.drop_column('follows', 'followedId')
    op.drop_column('follows', 'userId')
    op.add_column('messages', sa.Column('receiverid', sa.Integer(), nullable=False))
    op.drop_constraint('messages_receiverId_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiverid'], ['id'])
    op.drop_column('messages', 'receiverId')
    op.add_column('tags', sa.Column('postid', sa.Integer(), nullable=True))
    op.drop_constraint('tags_postId_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'posts', ['postid'], ['id'])
    op.drop_column('tags', 'postId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_postId_fkey', 'tags', 'posts', ['postId'], ['id'])
    op.drop_column('tags', 'postid')
    op.add_column('messages', sa.Column('receiverId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_receiverId_fkey', 'messages', 'users', ['receiverId'], ['id'])
    op.drop_column('messages', 'receiverid')
    op.add_column('follows', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('followedId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key('follows_followedId_fkey', 'follows', 'users', ['followedId'], ['id'])
    op.create_foreign_key('follows_userId_fkey', 'follows', 'users', ['userId'], ['id'])
    op.drop_column('follows', 'followedid')
    op.drop_column('follows', 'userid')
    op.create_table('post_likes',
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('postId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], name='post_likes_postId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='post_likes_userId_fkey'),
    sa.PrimaryKeyConstraint('userId', 'postId', name='post_likes_pkey')
    )
    op.drop_table('post_like')
    # ### end Alembic commands ###
