"""empty message

Revision ID: 5c54e2f62083
Revises: a720f41a6bd4
Create Date: 2022-02-08 11:39:35.297512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c54e2f62083'
down_revision = 'a720f41a6bd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('userid', sa.Integer(), nullable=True),
                    sa.Column('postid', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
                    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('post_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
                    sa.Column('userId', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.Column('postId', sa.INTEGER(),
                              autoincrement=False, nullable=False),
                    sa.ForeignKeyConstraint(
                        ['postId'], ['posts.id'], name='post_likes_postId_fkey'),
                    sa.ForeignKeyConstraint(
                        ['userId'], ['users.id'], name='post_likes_userId_fkey'),
                    sa.PrimaryKeyConstraint(
                        'userId', 'postId', name='post_likes_pkey')
                    )
    op.drop_table('post_like')
    # ### end Alembic commands ###
