"""empty message

Revision ID: 19a1ca9625e0
Revises:
Create Date: 2022-02-04 12:44:03.210846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a1ca9625e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('bio', sa.String(length=150), nullable=True),
    sa.Column('avatar_url', sa.String(length=600), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('follows',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('followedid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followedid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userid', 'followedid')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('receiverid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=1000), nullable=False),
    sa.ForeignKeyConstraint(['receiverid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=600), nullable=False),
    sa.Column('description', sa.String(length=2200), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=2200), nullable=False),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_likes',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('userid', 'postid')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postid', sa.Integer(), nullable=True),
    sa.Column('hashtag', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['postid'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('post_likes')
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('messages')
    op.drop_table('follows')
    op.drop_table('users')
    # ### end Alembic commands ###
